CREATE DATABASE dbNUEVA
GO

USE dbNUEVA
GO

CREATE TABLE ROLES(
IdRol INT PRIMARY KEY IDENTITY,
Descripcion VARCHAR(50),
Nivel INT,
Area VARCHAR(2)
)
GO

INSERT INTO ROLES(Descripcion,Nivel,Area) VALUES
('ADMIN', 1, 'AD');

CREATE TABLE PERMISOS(
IdPermiso INT PRIMARY KEY IDENTITY,
NombreMenu VARCHAR(50) NOT NULL,
IdRol INT REFERENCES ROLES(IdRol) NOT NULL
)
GO

INSERT INTO PERMISOS(NombreMenu,IdRol) VALUES
('Reporte Administración',1)

CREATE TABLE UBICACIONES(
IdUbicacion INT PRIMARY KEY IDENTITY,
Pais VARCHAR(32) NOT NULL,
Estado VARCHAR(32) NOT NULL,
Calle VARCHAR(32),
Municipio VARCHAR(32),
Colonia VARCHAR(32),
CodigoPostal VARCHAR(16),
NumeroExterior VARCHAR(16),
Longitud DECIMAL(10,7) NOT NULL,
Latitud DECIMAL(10,7) NOT NULL
)
GO

CREATE TABLE PERSONAL(
IdPersona INT PRIMARY KEY IDENTITY,
Celular VARCHAR(16),
ApellidoPaterno VARCHAR(32) NOT NULL,
ApellidoMaterno VARCHAR(32) NOT NULL,
Nombres VARCHAR(64) NOT NULL,
Usuario VARCHAR(20) NOT NULL UNIQUE,
Clave VARCHAR(255),
FechaExpiracionClave DATE,
IdRol INT REFERENCES ROLES(IdRol) NOT NULL,
Activo BIT NOT NULL DEFAULT 1,
Mail VARCHAR(64),
FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
FechaIngreso DATETIME NOT NULL,
RutaImagen VARCHAR(2048),
FechaNacimiento DATE,
RFC VARCHAR(64),
NumEmpleado INT,
NumImss VARCHAR(16),
Curp VARCHAR(32),
IdUbicacion INT REFERENCES UBICACIONES(IdUbicacion)
)
GO

INSERT INTO PERSONAL(Nombres, ApellidoPaterno, ApellidoMaterno,Usuario,Clave,IdRol,Activo,Mail,FechaIngreso) VALUES
('José', 'Gonzalez', 'Gonzalez', 'ADMIN','$2b$10$tmYofvksT5grvX1vaC2.m./qmlGbsgu5lj2d90vl0.Y/HFHoe1DCW',
1,1,'joseGonzalez@prueba.com.mx',GETDATE());

CREATE TABLE SESIONES( 
IdSesion INT IDENTITY PRIMARY KEY, 
IdPersona INT REFERENCES PERSONAL(IdPersona), 
RefreshToken VARCHAR(MAX), 
Dispositivo VARCHAR(255), 
DirIp VARCHAR(50), 
Activa BIT NOT NULL DEFAULT 1, 
FechaCreacion DATETIME DEFAULT GETDATE(), 
FechaExpiracion DATETIME,
UltimaActividad DATETIME
)
GO

CREATE TABLE TOKENS_REVOCADOS (
IdTokenRevocado INT PRIMARY KEY IDENTITY,
Jti VARCHAR(36) UNIQUE,
FechaCreacion DATE NOT NULL DEFAULT GETDATE(),
IdPersona INT REFERENCES PERSONAL(IdPersona)
)
GO

CREATE TABLE LOGIN_ATTEMPTS (
IdLoginAttempt INT IDENTITY PRIMARY KEY,
Usuario VARCHAR(100),
DirIp VARCHAR(50),
Dispositivo VARCHAR(255),
Exitoso BIT,
Fecha DATETIME NOT NULL DEFAULT GETDATE(),
Razon VARCHAR(64)
)
GO

CREATE TABLE LOGS_HISTORIAL(
IdLog INT PRIMARY KEY IDENTITY,
Titulo VARCHAR(20),
SubTitulo VARCHAR(20),
Accion VARCHAR(10),
Referencia VARCHAR(200),
FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
IdPersona INT REFERENCES PERSONAL(IdPersona)
)
GO